from pybricks.tools import wait
from drive import drive
from hub import wait_for_button_pressed
from wall import wall

def run3():
    wall.rightTo(-8, wait=False)
    drive.drive_to(415,0)
    wall.upTo(35)
    wait(50)
    #wait_for_button_pressed()
    wall.upTo(60, wait=False)
    drive.drive_to(30,0, speed=140) 
    #wait_for_button_pressed()
    wait(50)
    wall.upTo(115, wait=False)
    drive.drive_to(70, 0, speed=100)
    wait(20)
    #wait_for_button_pressed()
    drive.drive_to(15, 0, speed=260)
    wall.upTo(90)
    #wait_for_button_pressed()
    drive.drive_to(-115,0)
    wall.rightTo(0)
    drive.rotate_to_forward(36)
    #wait_for_button_pressed()
    wall.upTo(55, wait=False)
    drive.drive_to(370, 37)
    #wait_for_button_pressed()
    wall.upTo(10)
    wall.upTo(45)
    #wait_for_button_pressed()
    drive.drive_to(-225,37)
    drive.rotate_to_backward(90)
    #wait_for_button_pressed()
    wall.upTo(0, wait=False)
    drive.drive_to(50, 90, speed=300)
    #wait_for_button_pressed()
    drive.drive_to(150, 90, speed=300)
    #wait_for_button_pressed()
    wall.rightTo(-5)
    wall.rightTo(2)
    wall.rightTo(0)
    #wait_for_button_pressed()
    drive.drive_to(-100,90, speed=190)
    drive.rotate_to_backward(35)
    wall.upTo(5, wait=False)
    wall.rightTo(55, wait=False)
    drive.straight_ms(1500, -400)
    #wall.upTo(5) #nur wenn ohne dreizack
